WeTTY Server
inovex/lfs458-course-prep pull request #69
Opened 2021-12-03 13:55 UTC by maxbischoff

Add another machine that hosts one [WeTTY](https://github.com/butlerx/wetty) container for each machine, behind a nginx proxy that does TLS Authentication and enforces HTTP basic-auth with individual passwords for each student.

2021-12-03 18:13 UTC, henninge requested changes
Sehr cool, vielen Dank! Da steckt viel Arbeit & Experimentieren drin, bis alles zusammen gespielt hat, stimmt's?

Ich habe auch nur zwei kleine Anmerkungen.

2021-12-03 18:13 UTC, henninge commented on modules/wetty_server/versions.tf
> +      version = "2.1.0"
Hier sollte auch ">=" oder "~" stehen, statt diesers exakten Version, oder nicht?

2021-12-03 18:13 UTC, henninge commented on variables.tf
> +    trainer_email = "only required when enabled=1"
```suggestion
  description = "config for wetty server, disabled by default"
  type = object({
    enabled       = bool,
    trainer_email = string
  })
  default = {
    enabled       = false
    trainer_email = "only required when enabled"
```

2021-12-06 08:17 UTC, maxbischoff commented on main.tf
> +  count = var.wetty_config.enabled
Ah, auf die Idee bin ich gar nicht gekommen, sehr gut!

2021-12-06 08:52 UTC, maxbischoff commented
> Sehr cool, vielen Dank! Da steckt viel Arbeit & Experimentieren drin, bis alles zusammen gespielt hat, stimmt's?
> 
> Ich habe auch nur zwei kleine Anmerkungen.

Ja, definitiv, hatte aber auch ein paar ganz gute Quellen für die nginx und certbot config und die vorgeschlagene nginx.conf von wetty selbst konsultiert. Die Quellen habe ich jetzt noch als Kommentare in den jeweiligen files hinzugefügt.

2021-12-06 13:03 UTC, henninge commented on modules/wetty_server/nginx.conf
> +      proxy_pass http://wetty-mbischoff-cp:3000/${name};
Ups! Was soll da eigentlich stehen? Der Name vom Docker-Container?

2021-12-06 13:07 UTC, maxbischoff commented on modules/wetty_server/nginx.conf
> +      proxy_pass http://wetty-mbischoff-cp:3000/${name};
ja, wetty-${name} müsste das glaube ich sein.

2021-12-06 13:08 UTC, maxbischoff commented on modules/wetty_server/nginx.conf
> +      proxy_pass http://wetty-mbischoff-cp:3000/${name};
Komisch, dass mir das beim testen nicht aufgefallen ist 🤔

2022-01-11 14:52 UTC, dirkcjelli approved these changes
Richtig gut <3

2022-01-11 14:54 UTC, merged