Switch to Ubuntu 20.04 and some maintainance
inovex/lfs458-course-prep pull request #71
Opened 2022-03-13 11:54 UTC by frittentheke

2022-03-20 12:28 UTC, theinrichs approved these changes
lgtm

2022-03-29 10:38 UTC, hikhvar requested changes

2022-03-29 10:38 UTC, hikhvar commented on main.tf
> +## REMOTE STATE
Why is this commented? If not used, please remove it.

2022-03-29 18:17 UTC, hikhvar approved these changes

2022-03-29 18:17 UTC, merged