Add DNS for student machines, fix solutions_patch
inovex/lfs458-course-prep pull request #75
Opened 2022-07-15 13:44 UTC by dirkcjelli

this PR 

* adds DNS entries for student machines
* fixes missing student_patch variable
* `terraform fmt`

2022-08-01 07:59 UTC, henninge requested changes
Hey, super Sache! Ich bin immer dafür, DNS zu nutzen wo geht. Hab nur eine klitzekleine Bitte  (siehe Kommentar).

2022-08-01 07:59 UTC, henninge commented on modules/student_workspace/data.tf
> +data "openstack_dns_zone_v2" "terraform" {
Hm, ich finde "terraform" dann doch etwas sehr generisch. Ist ja alles terraform hier ...
Vorschlat: "dns_domain"  Wäre zwar nur ein bisschen weniger generisch, stellt aber ggf. den Bezug zu "var.dns_domain" her.

2022-08-01 13:07 UTC, dirkcjelli commented on modules/student_workspace/data.tf
> +data "openstack_dns_zone_v2" "terraform" {
done

2022-08-03 20:49 UTC, henninge reviewed
Der Build failt. Sorry, dachte das hättest du gesehen.

2022-08-04 13:44 UTC, henninge commented
In `modules/wetty_server/data.tf` fehlt die data source  `dns_domain`.  Dort steckt sie in `main.tf` und heißt noch immer `terraform`. Würde ich eben schnell selber fixen, kann ja aber hier nix pushen ...

2022-08-06 10:22 UTC, henninge approved these changes
Danke schön!

2022-08-17 08:39 UTC, maxbischoff approved these changes
LGTM

2022-08-17 09:54 UTC, merged